name: Auto Update Sitemap for watchingtrending.click

on:
  # Trigger khi Cloudflare Pages build xong
  workflow_run:
    workflows: ["Pages build and deployment"]
    types:
      - completed
  # Cũng có thể trigger khi push lên main (dự phòng)
  push:
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install sitemap generator
        run: npm install -g sitemap-generator-cli

      - name: Generate sitemap.xml
        run: |
          npx sitemap-generator-cli https://watchingtrending.click \
            --output ./sitemap.xml \
            --max-depth 3 \
            --strip-querystring true \
            --last-mod true

      - name: Commit updated sitemap
        run: |
          git config user.name "LEDO-DEV"
          git config user.email "levando.oscar@gmail.com"
          git add sitemap.xml || true
          git diff --cached --quiet || git commit -m "Auto-update sitemap.xml [skip ci]"
          git push https://LEDO-DEV:${{ secrets.GH_TOKEN }}@github.com/LEDO-DEV/Watching_Trending.git main

      - name: Ping Google & Bing to reindex
        run: |
          curl -s "https://www.google.com/ping?sitemap=https://watchingtrending.click/sitemap.xml" || true
          curl -s "https://www.bing.com/ping?sitemap=https://watchingtrending.click/sitemap.xml" || true
